# Generated by Django 5.0.7 on 2024-12-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0003_investmentoption_remove_userprofile_profit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
