# Generated by Django 5.0.7 on 2024-12-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0004_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='loan_balance',
        ),
        migrations.AddField(
            model_name='investment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
